### ISSUE TITLE
[Bug] Ignoring All Config Changes

### ISSUE THREAD

**Issue by SaltSouls** [TheASEStefan/ZombiesReworkedMod#1]
Changing things in the latest version of the mods config doesn't seem to actually affect what the zombies are capable of. I turned off their upgraded equipment and the ability to use things like flint and steel, and the totem of undying. Yet I have still seen zombies with the upgraded equipment and even saw one actively use a totem.

**Comment by TheASEStefan** [comment]
Did you use Mr Crayfish's Configured mod to configure these settings? Either way, restart minecraft because it should work.

**Comment by TheASEStefan** [comment]
> Changing things in the latest version of the mods config doesn't seem to actually affect what the zombies are capable of. I turned off their upgraded equipment and the ability to use things like flint and steel, and the totem of undying. Yet I have still seen zombies with the upgraded equipment and even saw one actively use a totem.

Did you use Mr Crayfish's Configured mod to configure these settings? Either way, restart minecraft because it should work.

**Comment by SaltSouls** [comment]
configured hasn't been updated to 1.20.1. I mad these changes to the config file directly.

**Comment by TheASEStefan** [comment]
> configured hasn't been updated to 1.20.1. I mad these changes to the config file directly.

Restart minecraft as I said, it should work!

**Comment by SaltSouls** [comment]
> Restart minecraft as I said, it should work!

I did. Sorry to say that the zombies were still spawning with the upgraded equipment and able to use totems. Also, I've noticed that the item in the zombies off hand will change between the player dying and respawning.

**Comment by TheASEStefan** [comment]
> > Restart minecraft as I said, it should work!
> 
> I did. Sorry to say that the zombies were still spawning with the upgraded equipment and able to use totems. Also, I've noticed that the item in the zombies off hand will change between the player dying and respawning.

Hmm okay, I know about the second thingy, it was meant to be like that. But what did you modify for the first one? For now there's no config option to toggle on/off armor spawning on mobs, I forgot about it, but I'll probably add it. And did you set totem use or whatever is called in the zombiesreworkedconfig? Either way, if that doesn't work even though it should ( maybe I got something wrong there ) go into the zombies reworked data and you can make it so that they can't spawn with totems and other items, therefore disabling their unique abilities.
